<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Title>Pict.Net</Title>
    <Authors>Nigel Bess</Authors>
    <Description>A minimalist .NET Wrapper for the Microsoft PICT API</Description>
    <PackageProjectUrl>https://github.com/NigelBess/PictNet</PackageProjectUrl>
    <PackageLicenseFile>LICENSE.TXT</PackageLicenseFile>
    <PackageReadmeFile>README.md</PackageReadmeFile>
	<Version>1.0.3</Version>
  </PropertyGroup>

 <ItemGroup>
    <None Include="..\LICENSE.TXT">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

<ItemGroup>
	<!-- Windows DLL -->
	<None Include="..\pictApiDll\$(Configuration)\PictApi.dll"
			Pack="true"
			PackagePath="runtimes/win-x64/native" />

	<!-- Linux SO -->
	<None Include="..\pictApiSo\bin\x64\$(Configuration)\libPictApi.so"
			Pack="true"
			PackagePath="runtimes/linux-x64/native" />
</ItemGroup>

</Project>
