<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Title>Pict.Net</Title>
    <Authors>Nigel Bess</Authors>
    <Description>A minimalist .NET Wrapper for the Microsoft PICT API</Description>
    <PackageProjectUrl>https://github.com/NigelBess/PictNet</PackageProjectUrl>
    <PackageLicenseFile>LICENSE.TXT</PackageLicenseFile>
    <PackageReadmeFile>README.md</PackageReadmeFile>
	<Version>1.0.1</Version>
  </PropertyGroup>

	<ItemGroup>
		<None Include="pictApiDll.dll" Pack="true" PackagePath="runtimes/win-x64/native">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>
	
  <ItemGroup>
    <EmbeddedResource Include="pictApiDll.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Include="..\LICENSE.TXT">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>
